/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ipc_jni_NativeBridge */

#ifndef _Included_com_example_ipc_jni_NativeBridge
#define _Included_com_example_ipc_jni_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ipc_jni_NativeBridge
 * Method:    process
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ipc_jni_NativeBridge_process
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
